`callback_url` should be redefined to let namecheap use google analytics tags in their params
rachel-carvalho/omniauth-namecheap pull request #1
Opened 2018-04-11 16:44 UTC by sophiedeziel

Hi Rachel!

2018-04-17 14:05 UTC, rachel-carvalho requested changes
Hey Sophie :)

Sorry I took so long to check your PR, I was on vacation 🎉

2018-04-17 14:05 UTC, rachel-carvalho commented on lib/omniauth/strategies/namecheap.rb
> +        full_host + script_name + callback_path
Looking at the source for [this method](https://github.com/omniauth/omniauth/blob/master/lib/omniauth/strategy.rb#L439), it seems that we're removing the query string here. Could you add a test that shows it?

2018-05-23 19:25 UTC, rachel-carvalho commented
I'll close this PR because I realized that it wasn't the `callback_url` that was wrong, but the `redirect_uri` that we were passing when trying to retrieve the token. It didn't match the original one we passed on the request phase and that's why it was being denied.

2018-05-23 19:25 UTC, closed without merging

2018-05-23 19:41 UTC, sophiedeziel commented
Yay!